### Python Basics

In [36]:
import numpy as np

In [37]:
# common operations

x = 4
y = 2

print(x%y)    # remainder

# listed by precedence, unless parenthesis

print(x**y)   # power
print(x*y)    # multiplication
print(x/y)    # division
print(x+y)    # addition
print(x-y)    # subtraction


0
16
8
2.0
6
2


In [38]:
# strings and manipulations (strings are immutable)

h = 'hello world'
food = 'apple'

print(h+' '+food)
print(h*2)
print(len(h))  # note it takes into account spaces
print(len(food))
print(h[0])    #slicing
print(h[0:3])
print(h[:])
print(h[-1])
print(h[::-1])  # slicing with skips
print(h[1:7:2])

hello world apple
hello worldhello world
11
5
h
hel
hello world
d
dlrow olleh
el 


In [39]:
# comparison operators

x = 4
y = 2

print(x > y)    
print(x >= y)  # greater than or equal to
print(x < y)
print(x <= y)  # less than or equal to
print(x == y)  # is equal to
print(x != y)  # is not equal to

True
True
False
False
False
True


In [64]:
# data structure types

a = (1,2,3,4)   #tuple, immutable , parenthesis
b = [1,2,3,4]   #list, mutable, brackets
c = 1,2,3,4, 'pet'     #strings, no enclosure
d = {'Ana': 'one', 'James': 2, 'Carl':'three'}   #dictionary key, value pairs, curly brackets
e = np.random.randint(100, size=(2, 3))    #matrix, array of arrays
print(e)

[[63 56 74]
 [46 92 66]]


In [65]:
#iterations

for i in a:
    print(i)
    
for i in b:
    print(i)
    
for i in c:
    print(i)
    
for index in d:        # could also print index,values
    print(index)
    
for i in e:
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4
pet
Ana
James
Carl
[63 56 74]
[46 92 66]


In [66]:
# indexing starts at 0

print(a[1])   #list/tuples same index
print(b[0])   #list/tuples same index
print(d.get('Ana'))  #index by keys
print(e[0,0])        # stipulat row,column

2
1
one
63


In [67]:
# reverse index, get index of values

print(a.index(2))
print(b.index(1))
print([k for k,v in d.items() if v == 'one'])      #dictionaries need list comprehension to get index by values
index = np.where(e==15)  #use np.where
print(index)

1
0
['Ana']
(array([], dtype=int64), array([], dtype=int64))


In [68]:
# tuples are immutable 

a[0] = 1

TypeError: 'tuple' object does not support item assignment

In [69]:
# list of lists evaluation

l = [1,2,3,4,[5,6,7]]   # inside the brackets count as 1
print(len(l))

5


In [70]:
# lists are mutable, it will change your original assignment (mutation)

b[0] = 5
print(b)

# list operations

b.append(9) # can also use extend
print(b)

del b[1] # delete by index
print(b)

b.remove(5)  # delete by element
print(b)

b.pop()  # delete last element, return deleted value

[5, 2, 3, 4]
[5, 2, 3, 4, 9]
[5, 3, 4, 9]
[3, 4, 9]


9

In [78]:
# list/string conversion
 
s = 'dog'     # s is a string
sl = list(s)  # sl is a list
print(sl)

print(''.join(sl))    # returns string
print('_'.join(sl))


['d', 'o', 'g']
dog
d_o_g


In [93]:
# list operations

w = [100,59,40,60] 
print(sorted(w))             #sorted does not mutate 
print(w)


# following will mutate, mutation will return NONE when called

w.sort()
print(w)

w.reverse()
print(w)


# clone list

b = [1,2,3,4]
b_clone = b.copy()     # can also use b_clone = b[:]
print(b_clone)


[40, 59, 60, 100]
[100, 59, 40, 60]
[40, 59, 60, 100]
[100, 60, 59, 40]
[1, 2, 3, 4]


In [42]:
# more iterations

for i in a:
    if i == 3:
        print(a.index(i))
        

        
power_four = lambda x: (x**4)
print(power_four(e))


z = zip(a,b)
print(list(z))


for i, value in enumerate(d):   #enumerate replace indexing to the [0] row
    print(i, value)

2
[[     625  7890481 84934656]
 [15752961 78074896  2560000]]
[(1, 1), (2, 2), (3, 3), (4, 4)]
0 Ana
1 James
2 Carl


In [101]:
# exceptions

a = 5
b = 'two'
print(a+b)   #regular error message

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [103]:
try:
    a = 5
    b = 'two'
    print(a+b)
    
except:
    print("Bug in user input.")  # replace error message with out own

Bug in user input.
