In [54]:
import numpy as np

In [81]:
# data structure types

a = (1,2,3,4)   #tuple, mutable , parenthesis
b = [1,2,3,4]   #list, immutable, brackets
c = 1,2,3,4, 'pet'     #strings, no enclosure
d = {'Ana': 'one', 'James': 2, 'Carl':'three'}   #dictionary key, value pairs, curly brackets
e = np.random.randint(100, size=(2, 3))    #matrix, array of arrays
print(e)

[[76 84 49]
 [ 9 92 75]]


In [63]:
# indexing starts at 0

print(a[1])   #list/tuples same index
print(b[0])   #list/tuples same index
print(d.get('Ana'))  #index by keys
print(e[0,0])        # stipulat row,column

2
1
one
0.17498741505228033


In [80]:
# reverse index, get index of values

print(a.index(2))
print(b.index(1))
print([k for k,v in d.items() if v == 'one'])      #dictionaries need list comprehension to get index by values
index = np.where(e==15)  #use np.where
print(index)

1
0
['Ana']
(array([0, 0], dtype=int64), array([0, 2], dtype=int64))


In [126]:
#transformations/mutations

print(a*2)   # tuple cannot subtract/add/divide by int with common notations, but can remove/replace
print(b*2)   # list cannot subtract/add/divide by int with common notations, list are immutable so no mutations
d['new'] = 3 # can remove item using del d['key'] , or d.pop('key')
print(d)
print(e*2)   #matrix multiplications inline with common operators
print(e/2)
print(e^2)
print(e.dot(e.T))

(1, 2, 3, 4, 1, 2, 3, 4)
[1, 2, 3, 4, 1, 2, 3, 4]
{'Ana': 'one', 'James': 2, 'Carl': 'three', 'new': 3}
[[152 168  98]
 [ 18 184 150]]
[[38.  42.  24.5]
 [ 4.5 46.  37.5]]
[[78 86 51]
 [11 94 73]]
[[15233 12087]
 [12087 14170]]


In [114]:
#iterations

for i in a:
    print(i)
    
for i in b:
    print(i)
    
for i in c:
    print(i)
    
for index in d:        # could also print index,values
    print(index)
    
for i in e:
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4
pet
Ana
James
Carl
new
[76 84 49]
[ 9 92 75]


In [136]:
# more iterations

for i in a:
    if i == 3:
        print(a.index(i))
        

        
power_four = lambda x: (x**4)
print(power_four(e))


z = zip(a,b)
print(list(z))


for i, value in enumerate(d):   #enumerate replace indexing to the [0] row
    print(i, value)

2
[[33362176 49787136  5764801]
 [    6561 71639296 31640625]]
[(1, 1), (2, 2), (3, 3), (4, 4)]
0 Ana
1 James
2 Carl
3 new
